## 部署
- name: OpenCart
  hosts: all
  become: yes
  become_method: sudo  
  vars_prompt:
    - name: 'webserver_select'
      prompt: "\nWhich Web-Server do you want to use? [ 1/2 ] \n\n
      1: Apache\n
      2: Nginx\n"
      private: no
      default: 1

    - name: 'opencart_version_select'
      prompt: "\nWhich opencart do you want to install? [ 1/2 ] \n\n
      1. Original edition
      2. 光大网络版"
      prinvate: no
      default: 1

  vars:
    temp_webserver_var:
      '1': 'apache'
      '2': 'nginx'
    temp_opencart_var:
      '1': 'Original edition'
      '2': '光大网络版'

    opencart_webs: "{{temp_webserver_var[webservr_select]}}"
    opencart_type: "{{temp_opencart_var[opencart_version_select]}}" 
  
  vars_files:
    - vars/main.yml

  roles:
    - {role: role_common, tags: "role_common"}
    - {role: role_cloud, tags: "role_cloud"}
    - {role: role_apache, tags: "role_apache", when: opencart_webs == 'apache'}
    - {role: role_nginx, tags: "role_nginx", when: opencart_webs == 'nginx'}
    - {role: role_mysql, tags: "role_mysql"}
    - {role: role_php-fpm, tags: "role_php-fpm"}
    - {role: role_inotify_watch, tags: "role_inotify_watch"}
    - {role: role_lamp, tags: "role_lamp", when: opencart_webs == 'apache'}
    - {role: role_lnmp, tags: "role_lnmp", when: opencart_webs == 'nginx'}
    - {role: role_phpmyadmin, tags: "role_phpmyadmin"}
    - {role: role_9panel, tags: "role_9panel"}
    - {role: role_redis, tags: "role_redis"}
    - {role: opencart, tags: "opencart"}
    - {role: role_init_password, tags: "role_init_password"}
    - {role: role_end, tags: "end"}
