## 部署
- name: OpenCart
  hosts: all
  become: yes
  become_method: sudo  
  vars_files:
    - vars/main.yml
  vars_prompt:
    - name: 'webs_selection'
      prompt: "\nWhich Web-Server do you want to use? [ 1/2 ] \n\n
      1: Apache\n
      2: Nginx\n"
      private: no
      default: 1

    - name: 'distribution_selection'
      prompt: "\nWhich distribution of OpenCart do you want to install? [ 1/2 ] \n\n
      1. Official original\n
      2. Chinese\n"
      private: no
      default: 1

  vars:

    webs_select:
      '1': 'apache'
      '2': 'nginx'

    infrastructure_select:
      '1': 'LAMP'
      '2': 'LNMP'

    distribution_select:
      '1': 'original'
      '2': 'chinese'

    opencart_distribution: "{{distribution_select[distribution_selection]}}"  
    opencart_webs: "{{webs_select[webs_selection]}}"
    phpmyadmin_webs: "{{webs_select[webs_selection]}}" 
    w9panel_webs: "{{webs_select[webs_selection]}}" 
    w9panel_set_infrastructure: "{{infrastructure_select[webs_selection]}}" 
    w9panel_set_apps: 
      - OpenCart
  
  pre_tasks:
    - include_vars: roles/role_cloud/vars/cloud_download_url.yml
      when: region == '1' or region == 1

    - debug:
        msg: OpenCart will be installed on {{w9panel_set_infrastructure}}, OS is {{ansible_distribution}}, region code is {{region}}

  roles:
    - {role: role_cloud, tags: "role_cloud"}
    - {role: role_php-fpm, tags: "role_php-fpm"}
    - {role: opencart, tags: "opencart"}