---
#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php-fpm/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    opencart_vhost_dir: "{{php_runtime_meta[ansible_os_family][opencart_webs].vhost_dir}}"
    opencart_vhost_src: "{{php_runtime_meta[ansible_os_family][opencart_webs].vhost_src}}"
    opencart_service: "{{php_runtime_meta[ansible_os_family][opencart_webs].service}}"
    opencart_owner: "{{php_runtime_meta[ansible_os_family][opencart_webs].owner}}"

- debug:
    msg: runtime {{ opencart_vhost_dir }}, {{opencart_vhost_src}}, {{opencart_service}}, {{opencart_owner}}, {{opencart_webs}}, {{ansible_distribution}}

# Opencart
- name: Remove extra dir
  shell: rm -rf /data/wwwroot/*{{opencart_name}}*

- name: Create OpenCart directory
  file:
    path: /data/wwwroot/{{opencart_name}}
    state: directory
    mode: 0750

- name: Git OpenCart from {{opencart_download_url[original]}}
  git:
    repo: "{{opencart_download_url[original]}}"
    dest: /data/wwwroot/{{opencart_name}}
    version: "{{opencart_version}}"
  when: opencart_distribution == "original"


- name: Git OpenCart from {{opencart_download_url[chinese]}}
  unarchive:
    src: "{{opencart_download_url[chinese]}}"
    dest: /data/wwwroot/{{opencart_name}}
    remote_src: yes
  when: opencart_distribution == "chinese"

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{opencart_name}}" ]; then mv *{{opencart_name}}* {{opencart_name}}; fi

- block:
  - name: Download OpenCart language package
    unarchive:
      src: "{{ opencart_package_cn }}"
      dest: /opt
      remote_src: yes

  - name: move language sql to opencart source directory
    shell: mv -f /opt/opencart/upload/install/opencart.sql /data/wwwroot/opencart1/upload/install/

  - name: delete sql file
    file:
      path: /opt/opencart/upload/install/opencart.sql
      state: absent

  - name: move language package to opencart source code
    shell: cp -rf /opt/opencart/upload/* /data/wwwroot/opencart1/upload/

  - name: delete language package
    file: 
      path: /opt/opencart
      state: absent

  when:  opencart_language == "cn" and opencart_type == "original edition"

- name: move upload directory to opencart 
  shell: mv /data/wwwroot/opencart1/upload/* /data/wwwroot/opencart

- name: delete opencart1 directory
  file: 
    path: /data/wwwroot/opencart1
    state: absent

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{opencart_name}}" ]; then mv *{{opencart_name}}* {{opencart_name}}; fi

- name: Rename config-dist.php to config-dist.php
  shell: cp /data/wwwroot/opencart/config-dist.php /data/wwwroot/opencart/config.php
  
- name: Rename admin/config-dist.php to config-dist.php
  shell: cp /data/wwwroot/opencart/admin/config-dist.php /data/wwwroot/opencart/admin/config.php

# 系统通用
- name: Permission directory
  shell: |
     find /data/wwwroot -type d -exec chmod 750 {} \;
     find /data/wwwroot -not -type d -exec chmod 640 {} \;

# 根据不同的基础环境分别处理
- block:
  - name: change owner&group
    shell: chown -R {{opencart_owner}}:{{opencart_owner}} /data/wwwroot

  - name: Copy Apache or Nginx vhost configuration
    copy: src={{opencart_vhost_src}} dest={{opencart_vhost_dir}}
    
  - name: restart Apache or Nginx
    service: name={{opencart_service}} state=restarted enabled=yes